collections:
  authors:
    output: true
  news:
    output: true
  localshare:
    output: true
    
    
defaults:
  - scope:
      path: ""
      type: "news"
      values:
      layout: "new"
  - scope:
      path: ""
      type: "localshare"
      values:
      layout: "default"
  - scope:
      path: ""
      values:
      layout: "default"
