collections:
  authors:
    output: true
  news:
    output: true
  localshareda10798f8b9bb16bd2baddba911c5c7:
    output: true
    
    
defaults:
  - scope:
      path: ""
      type: "news"
      values:
      layout: "new"
  - scope:
      path: ""
      type: "localshareda10798f8b9bb16bd2baddba911c5c7"
      values:
      layout: "new"
  - scope:
      path: ""
      values:
      layout: "default"
